# Generated by Django 3.0.5 on 2020-04-09 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agencies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='noname', max_length=255)),
                ('parent', models.CharField(default='noname', max_length=255)),
                ('credibility_rate', models.CharField(default='noname', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SearchResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(default='noname', max_length=255)),
                ('date_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(default='noname', max_length=255)),
                ('link', models.CharField(default='noname', max_length=255)),
                ('source', models.CharField(blank=True, choices=[('N', 'NEWS API'), ('R', 'REDDIT')], default='N', max_length=1, null=True)),
                ('country', models.CharField(default='noname', max_length=2)),
                ('author', models.CharField(default='noname', max_length=128)),
                ('urlToImage', models.CharField(default='noname', max_length=512)),
                ('publishedAt', models.DateTimeField(default='noname', max_length=64)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Agencies')),
            ],
        ),
    ]
